### ISSUE TITLE
Incorrect port numbers on install guide page 3

### ISSUE THREAD

**Issue by wook1000** [NetAppDocs/ontap-systems#103]
Page: [Quick steps - AFF A800](https://docs.netapp.com/us-en/ontap-systems/a800/install-quick-guide.html)

In the linked PDF install guide the doc refers to e0c and e0f. These ports should be e5a and e5b
![image](https://user-images.githubusercontent.com/27678136/185549123-5a6a696d-dba0-4862-818c-77b5d0649156.png)

Slide 26 on this doc shows the port numbers: https://library.netapp.com/ecm/ecm_download_file/ECMLP2876580

**Comment by thrisun** [comment]
Thank you very much for your comment. We will correct the content and post it next week,
Again, thank you very much!

**Comment by ntap-bmegan** [comment]
@thrisun - It looks like the referenced document was updated. Can you confirm (and close the issue if so)?

**Comment by netapp-martyh** [comment]
@thrisun - Sundari, please confirm this is resolved and close out. Thanks!
