### ISSUE TITLE
Is a MSID reseat mandatory for NSE drives when replacing a NVMEM battery? 

### ISSUE THREAD

**Issue by amadorloureiro** [NetAppDocs/ontap-systems#106]
Page: [Replace the NVMEM battery - AFF A250](https://docs.netapp.com/us-en/ontap-systems/a250/nvmem-nvram-battery-replace.html)

For a NVMEM bat replacement is mentioned "If you are using NetApp Storage Encryption, you must have reset the MSID using the instructions in the “Returning SEDs to unprotected mode” section of the ONTAP 9 NetApp Encryption Power Guide." 

Is this real and mandatory? And how we should implement it? 

I cannot find that in our internal NET2 information for the engineers onsite.

**Comment by thrisun** [comment]
Hi Amador,
Thank you for bringing this to my attention. I will talk to the writers who made the decision to put that it and address it.
Thank you again for bringing this to my attention.
