### ISSUE TITLE
Link to "System data sheet" does not resolve

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/ontap-systems#108]
Page: [FAS500f System Documentation](https://docs.netapp.com/us-en/ontap-systems/fas500f/index.html)

The link to the system data sheet in the first tile points to this URL - https://www.netapp.com/ru/media/7819-ds-4020.pdf, but doesn't resolve. Instead, I'm taken to www.netapp.com home page.

Chrome Version 104.0.5112.102 (Official Build) (64-bit) on Windows 10 Enterprise Windows Feature Experience Pack 120.2212.4180.0

**Comment by thrisun** [comment]
Hi Adam, I fixed the issue Thursday evening and Marty posted on Monday, Labor Day. Per Ling, the Marketing lead for this PDF file, the link does resolve (there was a question mark missing in the original link). Hope this helps.
