### ISSUE TITLE
Automatic case suppression should apply to all scenarios, not just encryption

### ISSUE THREAD

**Issue by netapp-martyh** [NetAppDocs/ontap-systems#113]
Page: [Check onboard encryption keys - AFF A200](https://docs.netapp.com/us-en/ontap-systems/a200/bootmedia-encryption-preshutdown-checks.html)

Step two on this page suppresses automatic case suppression. This would apply to all systems undergoing a FRU replacement, not just if they have onboard encryption. It seems like this step should go in Shutting down the impaired controller.

Step in question:

If AutoSupport is enabled, suppress automatic case creation by invoking an AutoSupport message: system node autosupport invoke -node * -type all -message MAINT=number_of_hours_downh

The following AutoSupport message suppresses automatic case creation for two hours: cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h

**Comment by dougthomp** [comment]
Ok.  We need to turn auto support back on at then end.  Do you agree?  Problem is, not everyone has autosupport turned on.  When I checked a while back, I recall less than 50% had it turned on.  

I'll ping our TMEs and see what they know.

**Comment by netapp-martyh** [comment]
The command suppresses case creation for a specified number of hours, so we don't need to turn it back on:

MAINT=number_of_hours_downh

**Comment by dougthomp** [comment]
I see that.

**Comment by dougthomp** [comment]
Anyway, asking Andris Bell, Lueth and Andris added one of his field guys about uptake.

**Comment by dougthomp** [comment]
FWIW - uptake is about 63%, not counting USPS, which has about 34% uptake.

**Comment by dougthomp** [comment]
Talked with Andris on Friday about this.  He says turn it back on when done.  His reasoning was that turning  AutoSupport when finished is a best practice if the field person over-estimated how long the repair would take.  I tend to agree with him on that.
