### ISSUE TITLE
Restore Storage and Volume Encryption Functionality - Step reorder

### ISSUE THREAD

**Issue by jpick-66** [NetAppDocs/ontap-systems#119]
Page: [Recable the system and reassign disks - AFF A250](https://docs.netapp.com/us-en/ontap-systems/a250/controller-replace-recable-reassign-disks.html)
I have verified in the A200, A220, and A250 documentation for Controller Replacement (I have not verified other array models), that the "Restore Storage and Volume Encryption Functionality" step, currently documented in the "Complete System Restoration" section of the Controller replacement documentation, comes after the storage giveback step.  This step should be placed in the "Recable System" section, prior to node giveback.  If the array has an OKM and NVE/NAE, and storage giveback is completed, and the veto is overridden, without performing the key sync process, volumes will go offline.  I personally feel the steps in the documentation for replacing the MB should be re-ordered.

**Comment by thrisun** [comment]
Thank you for your comment; we will take care of this. The updates will be posted next week. Again, thank you very much, take care, and keep safe.

**Comment by jpick-66** [comment]
Hello.  I am not seeing the requested updates.  Any idea when these changes will be posted?

-Thx

**Comment by thrisun** [comment]
Hi,
Pardon my tardiness; I was out sick the past couple of days. I did address the issue and I just verified that the fix has been pushed and merged through the repo. Thank you for your patience, take care, and keep safe.

**Comment by jpick-66** [comment]
Thank You.  It looks much better.

-Jon
