### ISSUE TITLE
Incorrect front diagram of NS224 on A900 install guide / details steps

### ISSUE THREAD

**Issue by jhubert-netapp** [NetAppDocs/ontap-systems#121]
Page: [Detailed steps - AFF 900](https://docs.netapp.com/us-en/ontap-systems/a900/install_detailed_guide.html)

The picture for the NS224 shelf, is actually a DS224C/2246.  The shelf ID button on the NS224 is above the ID and is a recessed metal button.  It can be hard to locate, and we really should include the correct picture here.

**Comment by thrisun** [comment]
Thank you for your comment. We will take a look and have it addressed hopefully by next week.

**Comment by dougthomp** [comment]
Drafts of revisions sent to Jeff in email.

**Comment by dougthomp** [comment]
Diagram updated in Detailed Guide and ISI.

Docs will be posted by next Monday 1/10/23
