### ISSUE TITLE
Remove "green LED" text - wrong and superfluous

### ISSUE THREAD

**Issue by andris-ntap** [NetAppDocs/ontap-systems#122]
Page: [Replace hardware - AFF A400](https://docs.netapp.com/us-en/ontap-systems/a400/chassis-replace-move-hardware.html)

With the chassis replacement workflow, this "green LED" is both incorrect (because there's no green LED on a Katana fan) and it's not applicable because the replacement chassis is not powered at the time the fans are being inserted.

**Remove** this bullet:
**The fan LED should be green after the fan is seated and has spun up to operational speed.**

Also, remove this same bullet in the FAS8300/FAS8700 version of the doc:
https://docs.netapp.com/us-en/ontap-systems/fas8300/chassis-replace-move-hardware.html#step-2-move-the-fans

Thanks!
-Andris

**Comment by thrisun** [comment]
Thanks Andris! Doug will take a look at it.

**Comment by dougthomp** [comment]
Already looking at it.  :-)

**Comment by dougthomp** [comment]
Change made to A400 and 8300/8700.  Changes will go live this 11/11 0r 11/14.
