### ISSUE TITLE
Few Requests for A900 NVRAM Module

### ISSUE THREAD

**Issue by TimMcGue** [NetAppDocs/ontap-systems#124]
Page: [Replace the NVRAM module and/or NVRAM DIMMs - AFF A900](https://docs.netapp.com/us-en/ontap-systems/a900/nvram_module_or_nvram_dimm_replacement.html)

This document is fantastic.  We reviewed the doc after a few onsite activities and included some feedback in the attached document.  Feel free to reach out if you would like to talk about any of the points.

[a900 nvram doc feedback.docx](https://github.com/NetAppDocs/ontap-systems/files/10006227/a900.nvram.doc.feedback.docx)

**Comment by thrisun** [comment]
Thank you very much Tim! I have added Doug Thompson to follow up on this!

Take care, and keep safe!

**Comment by dougthomp** [comment]
Got it.  Will take a look and try to get to it this week.  I'm in the middle of prepping FAS2800 for QA review in early December.

**Comment by TimMcGue** [comment]
Thanks so much!

**Comment by netapp-martyh** [comment]
Thanks, Tim, as always for the feedback and the positive comment.

**Comment by TimMcGue** [comment]
Adjusting one comment from the attached doc.  Regarding the following line:

•	From the healthy controller, verify that any coredumps are saved:

I put a few comments there, but after more research we can actually remove that savecore step entirely.  

From: https://confluence.ngage.netapp.com/display/TOI/Boot+Device+Coredump

There no longer is a secondary savecore step required to produce a core. The core is dumped as raw contents to the boot device and is interpreted Just-In-Time when the core region on the boot devices is queried, read, or the core is extracted.

**Comment by thrisun** [comment]
Thank you for keeping our docs precise Tim! :-)

**Comment by dougthomp** [comment]
Tim:

Changes made.    They should be live by Monday 2/27.

Thanks again for the feedback.
