### ISSUE TITLE
AFF-A400 HA Interconnect Cabling MCCIP

### ISSUE THREAD

**Issue by tgoreham** [NetAppDocs/ontap-systems#125]
Page: [Detailed guide - AFF A400](https://docs.netapp.com/us-en/ontap-systems/a400/install-detailed-guide.html)

Noticed that [Cabling the controller peering, data, and management ports](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_cable_other_connections.html) links to the relevant non-MCCIP documentation for system cabling: [AFF and FAS System Documentation](https://docs.netapp.com/us-en/ontap-systems/)

If we look at the [A400 detailed guide](https://docs.netapp.com/us-en/ontap-systems/a400/install-detailed-guide.html) & [PDF](https://docs.netapp.com/us-en/ontap-systems/media/PDF/215-14510_2020_09_en-us_AFFA400_ISI.pdf), we see that e0a/e0b are always reserved for the HA interconnect (no exceptions for MCCIP are mentioned).

This is strange because when you install an AFF-A400 system for MCCIP, ports e0a/e0b are available for hosting data LIFs (usually in Default IPSpace), this should be highlighted as an exception in the documentation.

Here is an [example](https://smartsolve.netapp.com/#cdv?refasup=2022112616251637&view=horizontal&section=IFSTAT-A&asupids=2022112616251637) from one of our customers.

It has been raised by multiple Field Engineers that PS have been cabling the systems 'as documented' which means they have 2 wasted ethernet ports per node that could instead be used for front-end operations.

So... I've opened [Issue #240](https://github.com/NetAppDocs/ontap-metrocluster/issues/240) to get this configuration verified. If we decide to update the docs to include this information then I think we need to update the documentation here too. Maybe just a one-liner mentioning the 'exception' and then link to the [Cabling the controller peering, data, and management ports](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_cable_other_connections.html) page.

Please let me know if you have any questions about this.

**Comment by thrisun** [comment]
Doug, please coordinate with Chris Lueth and Olivia to address this.

**Comment by dougthomp** [comment]
Added note to Detailed guide:

"If you are cabling an MCC-IP configuration, ports e0a/e0b are available for hosting data LIFs (usually in Default IPSpace)."  Leaving ISI (aka install poster) as is. This addresses most common installation scenario.

Change will go live next Monday.

**Comment by netapp-martyh** [comment]
@dougthomp  - Be sure to say "MetroCluster IP" rather than MCC-IP.

**Comment by dougthomp** [comment]
Done
