### ISSUE TITLE
A220 Documentation Links to Incorrect Platform

### ISSUE THREAD

**Issue by WillFulmer** [NetAppDocs/ontap-systems#127]
A220 should link here:
https://docs.netapp.com/us-en/ontap-systems/a220/index.html

But - it currently links here:
https://docs.netapp.com/us-en/ontap-systems/fas2700/index.html

**Comment by dougthomp** [comment]
Jackie - Passing this off to you.  Link seems to work properly on my side, but I may not be seeing the issue.

**Comment by netapp-martyh** [comment]
Hi @WillFulmer -- On what page/URL are you seeing this incorrect link?

Thanks,
Marty

**Comment by dougthomp** [comment]
Closing this as a stale issue.
