### ISSUE TITLE
Variety of Notes

### ISSUE THREAD

**Issue by TimMcGue** [NetAppDocs/ontap-systems#128]
Page: [Replace the chassis - AFF A900](https://docs.netapp.com/us-en/ontap-systems/a900/chassis_replace_overview.html)
[a900 chassis  doc feedback.docx](https://github.com/NetAppDocs/ontap-systems/files/10250443/a900.chassis.doc.feedback.docx)

Attaching a few notes in Word document.  Once again a fantastic doc, just making a few notes from field support perspective.

**Comment by dougthomp** [comment]
Thanks Tim.  Still working on the NVRAM flyer - Technical difficulties with publishing it.  I'll get on this as soon as I can.

**Comment by dougthomp** [comment]
Finished the changes with the update of the shutdown and bring up sections in the called out flyers .
