### ISSUE TITLE
A few links to switches are broken

### ISSUE THREAD

**Issue by loganbaez** [NetAppDocs/ontap-systems#135]
Page: [AFF and FAS System Documentation](https://docs.netapp.com/us-en/ontap-systems/index.html)

the following return 404 error.

- [Broadcom-supported BES-53248](https://docs.netapp.com/us-en/ontap-systems-switches/switch-bes-53248/overview-bes53248.html)
- [Cisco 9336C-FX2](https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-9336c-fx2/9336-overview.html)
- [Cisco 9336-FX2 in shared configurations](https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-9336c-fx2-shared/9336c_setup_and_configuration_guide_for_cisco_shared_switches.html)

the links from this page work.
https://docs.netapp.com/us-en/ontap-systems-switches/

thank you

**Comment by netapp-yvonneo** [comment]
@loganbaez thanks for the feedback.

I'll update the links accordingly and let you know when they're available online.

**Comment by netapp-yvonneo** [comment]
@loganbaez all links have been updated. See here: https://docs.netapp.com/us-en/ontap-systems/index.html

Thanks for your feedback.
