### ISSUE TITLE
SSE Feedback on AFF A900 DCPM replacement

### ISSUE THREAD

**Issue by tullynet** [NetAppDocs/ontap-systems#137]
Page: [Replace the Destage Control Power Module containing the NVRAM11 battery - AFF A900](https://docs.netapp.com/us-en/ontap-systems/a900/dcpm_NVRAM11_battery_replace.html)

This doc is fantastic.  We had a couple of minor notes in regards to consistency.

I believe destage and de-stage are both technically correct, but whichever we use, we should be consistent throughout the doc.
Step 4 terra cotta button is a release button not a locking button according to the TOI
Same for the diagram. Terra cotta button is a release button not a locking button according to the TOI

**Comment by dougthomp** [comment]
Hi tullynet:

Thanks for the feedback and make adjustments.  Consistency is important.  I've seen destage both ways.  I think no hyphen is the proper terminology.

I'll change the button to release.

**Comment by tullynet** [comment]
I tend to agree with destage without the hyphen.  I pulled this from a console log of the boot process on an A800.

"NVDIMM pending and destage progressing....."

**Comment by dougthomp** [comment]
Changes made.  They should appear on the doc site by Monday 2/6.
