### ISSUE TITLE
SSE Feedback on I/O module replacement

### ISSUE THREAD

**Issue by tullynet** [NetAppDocs/ontap-systems#138]
Page: [Replace an I/O module - AFF A900](https://docs.netapp.com/us-en/ontap-systems/a900/pci_cards_and_risers_replace.html)

Under Step 3: Reboot the controller after I/O module replacement.
Step 3. If your system is configured to support 10 GbE cluster interconnect and data connections on 40 GbE NICs or onboard ports, convert these ports to 10 GbE connections by using the nicadmin convert command from Maintenance mode. 
The suggestion is to remove the reference to onboard ports (there aren’t any onboard ports on this platform)

Additionally, can we link to this doc of something similar for the nicadmin convert details? https://docs.netapp.com/us-en/ontap/networking/convert_40gbe_nic_ports_into_multiple_10gbe_ports_for_10gbe_connectivity.html

**Comment by dougthomp** [comment]
tullynet:  

Thanks for the feedback.  I have incorporated your comments into the doc. They should appear on docs.netap.com by Monday 2/6
