### ISSUE TITLE
SSE Feedback on Add an I/O module - AFF A900

### ISSUE THREAD

**Issue by tullynet** [NetAppDocs/ontap-systems#139]
Page: [Add an I/O module - AFF A900](https://docs.netapp.com/us-en/ontap-systems/a900/add_io_module.html)

Option 1: Add the I/O module to a system with open slots
You can add an I/O module into an empty module slot in your system as either a NIC or a storage module for the NS224 storage shelves.

We can also add SAS adapters, FC adapters for block access, and FC adapters for tape.  Suggestion is to remove the statement (You can add an I/O module into an empty module slot in your system as either a NIC or a storage module for the NS224 storage shelves.)

For step 1 the suggestion is to reuse the shut down steps from I/O replacement document as it should be the same process.

**Comment by dougthomp** [comment]
Hi tullynet:

Thanks for the feedback.  I'll look into it this week (week of 2/13) and address your concern.  

Doug Thompson 
NetApp Storage and Platform Information Engineering

**Comment by dougthomp** [comment]
Changes incorporated. They will go live by Monday 2/20
