### ISSUE TITLE
Need to clarify what SAS2/SAS3 mixed stack "all" and "bridge-attached" means

### ISSUE THREAD

**Issue by andris-ntap** [NetAppDocs/ontap-systems#145]
Page: [Hot-add IOM12/IOM12B shelves to a stack of IOM6 shelves](https://docs.netapp.com/us-en/ontap-systems/sas3/iom12-hot-add-mix.html)

The **bolded** section is the confusing part as is does not designate that for bridge attached it supports mixed stacks ONLY when connected through an ATTO (so MCC). 

Your system and version of ONTAP must support a mix of IOM6 shelves and IOM12/IOM12B shelves in the same stack (a mixed stack).
You can verify support by using one of the following methods:
•	Enter the run local sysconfig command, at the admin prompt of either controller.
If the SAS2/SAS3 Mixed Stack Support field does not appear in the output or has a value of none, then your system does not support mixed stacks.
**If anything else appears in the SAS2/SAS3 Mixed Stack Support field, such as all or bridge-attached, then your system does support mixed stacks.**

How does this change look? Replace that last line with these 2. 

If “all” appears in the SAS2/SAS3 Mixed Stack Support field, then your system supports mixed stacks.

If “bridge-attached” appears in the SAS2/SAS3 Mixed Stack Support field, then your system supports mixed stacks only if the storage shelves are connected through an ATTO FibreBridge.

**Comment by netapp-lisa** [comment]
Hi Andris, I made the change to the mixed stack doc. The updated doc will post by Monday 3/20. I'm not sure I can copy Rich on this so I'll send him an email,
