### ISSUE TITLE
can we add a reason why the BMC is being asked to be rebooted in step 7

### ISSUE THREAD

**Issue by ericd-netapp** [NetAppDocs/ontap-systems#147]
Is there a technical reason why we ask the customer to reboot the BMC during a card during Step 2: Replace I/O modules?

or is this something that should NOT be here.

Page: [Add an I/O module - AFF A900](https://docs.netapp.com/us-en/ontap-systems/a900/add_io_module.html)

**Comment by dougthomp** [comment]
Hi Eric:

Thanks for your feedback.  I cannot answer that question, but will find out!  If the doc needs updating, I will update it.

Thanks again, 
Doug Thompson

**Comment by dougthomp** [comment]
Hi Eric:

After doing some digging, there was a BURT for this issue late last summer.  [BURT ](https://burtview.netapp.com/burts/1494308#).  It looks like the issue has been resolved.  I'm removing the BMC step from the flyer.  I'll remove it from the FAS9500 version as well.

Again, thank you for the feedback.  The change should show up by Monday 3/27.

**Comment by ericd-netapp** [comment]
Thanks Doug.

Great info.  It looks to be resolved, but doesn’t address the fact that a customer could still hit this if they haven’t updated their SP firmware to a fixed release.

Is it not in style to add BURT info links to step 7 and have customer check if they have the right firmware?  Or is that just too detailed


-Eric
323.388.7727

**Comment by dougthomp** [comment]
Hi Eric:

I'll check on adding the link.  I haven't seen it, but that doesn't mean it isn't done in some cases.  I'll let you know what I find out.
