### ISSUE TITLE
SSE Feedback on AFF C250 System Documentation main page.

### ISSUE THREAD

**Issue by tullynet** [NetAppDocs/ontap-systems#151]
Page: [AFF C250 System Documentation](https://docs.netapp.com/us-en/ontap-systems/c250/index.html)

Under the "Add or remove shelves" section there is a link to SAS with IOM12 that should be removed as it's not supported on the platform.

**Comment by netapp-lisa** [comment]
Hi, thanks so much for catching that (and the other two "landing page" issues)! I was in the process of correcting this, but found out these landing pages are being redesigned, e.g. that tile for "Add or remove shelves" is being removed. I think this change will be made in the next week or so.
