### ISSUE TITLE
SSE Feedback on AFF C400 System Documentation main page

### ISSUE THREAD

**Issue by tullynet** [NetAppDocs/ontap-systems#152]
Page: [AFF C400 System Documentation](https://docs.netapp.com/us-en/ontap-systems/c400/index.html)

Under "Install and setup" Fabric and stretch metrocluster configuration links are provided, but the only supported configuration appears to be Metrocluster IP.

Under "Add or remove shelves" SAS with IOM12 is listed, and should be removed as it's not a supported configuration.  An NS224 document link should be added.

**Comment by netapp-lisa** [comment]
Thanks again for catching these errors on landing pages. I'm updating to replace stretch and fabric MetroCluster text/links with MCC-IP. And since the tile/box with the shelf info is being designed out, that's N/A. However, you still get points for catching it :-)
