### ISSUE TITLE
SSE Feedback on AFF C800 System Documentation main page

### ISSUE THREAD

**Issue by tullynet** [NetAppDocs/ontap-systems#153]
Page: [AFF C800 System Documentation](https://docs.netapp.com/us-en/ontap-systems/c800/index.html)

Under the "Add or remove shelves" section there is a link to SAS with IOM12 that should be removed as it's not supported on the platform.

**Comment by netapp-lisa** [comment]
Thanks, no action needed since the shelf tile/box is being designed out of the landing pages.
