### ISSUE TITLE
What happened to the PDF files? I can no longer see any option to open the files in PDF format.

### ISSUE THREAD

**Issue by JamieLove-Net2** [NetAppDocs/ontap-systems#154]
Page: [Replace a DIMM - AFF C400](https://docs.netapp.com/us-en/ontap-systems/c400/dimm-replace.html)

**Comment by netapp-lisa** [comment]
Hi Jamie, that's really weird! I asked our IE architect about it. I hope to have an answer for you today.

**Comment by netapp-lisa** [comment]
Okay, the PDF function just got turned back on.
