### ISSUE TITLE
A few encryption related requests

### ISSUE THREAD

**Issue by TimMcGue** [NetAppDocs/ontap-systems#159]
Page: [Check onboard encryption - AFF A400](https://docs.netapp.com/us-en/ontap-systems/a400/bootmedia-encryption-preshutdown-checks.html)

So in this command:
security key-manager key-query

There is no hyphen between key and query.  There are four places in this overall document that should be changed for that.

This part:
Enter the onboard security key-manager sync command: security key-manager external sync

Should read more like how it was in a previous step:
Restore the external key management authentication keys to all nodes in the cluster: security key-manager external restore

**Comment by dougthomp** [comment]
Hi Tim:

Thanks for the feedback.  I'm making the changes now and they should be live by Monday (4/17).
