### ISSUE TITLE
hooking back up the cables is missing

### ISSUE THREAD

**Issue by ericd-netapp** [NetAppDocs/ontap-systems#161]
Page: [Replace a DIMM - AFF A250](https://docs.netapp.com/us-en/ontap-systems/a250/dimm-replace.html)

On step 4, we tell the customer not to hook up all of the cables and then to run diags, but we never tell them to hook up the cables after diagnostics are run.  I guess it goes without saying that they should do that, but a customer called in about it today.

I know that the diagnostics are planning to be removed soon, but just some feedback to be sure we make sure they hook up the cables.

**Comment by netapp-lisa** [comment]
Thanks Eric. I see what you mean. I'll also take a look at other DIMM procedures for other platforms (we reuse some content across multiple platforms.) I'll let you know when it's fixed.

**Comment by dougthomp** [comment]
Hi Eric:

I'm closing this issue because it should be covered when we remove diagnostic steps from the FRU flyers.  

Thanks again for the feedback.  It was a great reminder to check that step.
