### ISSUE TITLE
No link to FAS data sheet. 

### ISSUE THREAD

**Issue by dougthomp** [NetAppDocs/ontap-systems#166]
Page: [AFF and FAS System Documentation](https://docs.netapp.com/us-en/ontap-systems/index.html)

There used to be one.  Also, on the "Learn about the AFF and FAS family of storage systems", the FAS link brings up an AFF datasheet (https://www.netapp.com/pdf.html?item=/media/19763-ds-3829.pdf).

**Comment by netapp-jsnyder** [comment]
The FAS datasheet is on the main landing page under the get started tile.

**Comment by dougthomp** [comment]
Yeah, it is, but it isn't  listed on https://docs.netapp.com/us-en/ontap-systems/index.html., where the others are listed too.
![image](https://github.com/NetAppDocs/ontap-systems/assets/76076341/74432e26-911f-4380-b3bd-d731477c61c3)
The item highlighted is for disk shelves.  We need a link to the FAS datasheet on this page, especially since A and C are listed.  Keep the storage datasheet and add the FAS link.
