### ISSUE TITLE
Please add some info about IOM12B module LEDs

### ISSUE THREAD

**Issue by andris-ntap** [NetAppDocs/ontap-systems#168]
### Page URL

https://docs.netapp.com/us-en/ontap-systems/sas3/service-monitor-leds.html

### Page title

Monitor disk shelf LEDs - shelves with IOM12/IOM12B modules

### Summary

Hi there...

We cover IOM12 module LEDs, currently. Since then, we have introduced the IOM12B module.

I think at a minimum, we can cover IOM12B by just stating it's "the same" as IOM12 in terms of LEDs. I.e. just add "or IOM12B" after every reference to IOM12 :-)

I don't think we have to go to the bother of adding an IOM12B section or even IOM12B module diagram - but bonus points if you do decide to do so.

Example changes (snippet):
### IOM12 or IOM12B module LEDs

The LEDs on the IOM12 or IOM12B module indicate whether the module is functioning normally, whether it is ready for I/O traffic, and whether there are any problems with the hardware.

The following table describes IOM12 or IOM12B module LEDs associated with the function of the module and the function of each SAS port on the module.

The IOM12 or IOM12B module is used in DS460C, DS224C, and DS212C disk shelves.

[Table updates, too]

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Thanks @andris-ntap. I'll liaise with Doug on getting this documentation update published.

**Comment by netapp-lisa** [comment]
Hi Paula, this one is mine :-)

**Comment by netapp-pcarriga** [comment]
Great, Lisa. Thanks for letting know.

**Comment by netapp-lisa** [comment]
Hi Andris, in the SAS3 monitoring LEDs where "IOM12" appears I updated to show, "IOM12/IOM12B" like in other places. I also added the graphic of the IOM12B module in the IOM LED section. You can see the changes here if you want. 
https://review.docs.netapp.com/us-en/ontap-systems_lisa-ontap-systems-hotfix-25may2023/sas3/service-monitor-leds.html#power-supply-leds 

These changes will go live tomorrow, Fri 26may.
