### ISSUE TITLE
can we remove running diagnostics on this and other procedures  (per burt 1543826)

### ISSUE THREAD

**Issue by ericd-netapp** [NetAppDocs/ontap-systems#173]
### Page URL

https://docs.netapp.com/us-en/ontap-systems/fas8300/caching-module-replace.html

### Page title

Replace the caching module - FAS8300 and FAS8700

### Summary

as per BURT 1543826 , can we have the diagnostic portion of this procedure removed?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ivanad** [comment]
Hi @ericd-netapp. We're in the process of removing diagnostic information. Just this feedback is fine; we'll take care of it. Thanks!

**Comment by ericd-netapp** [comment]
thanks!  I just got 2 separate calls on this earlier this week so I'm glad its' in the works!

**Comment by netapp-ivanad** [comment]
Diagnostic information has been removed from our FRU procedures and all changes are live!
