### ISSUE TITLE
odd toc structure

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/ontap-systems#175]
### Page URL

https://docs.netapp.com/us-en/ontap-systems/fas9000/install-detailed-guide.html

### Page title

Detailed guide - AFF A700 and FAS9000

### Summary

The PDF menu reflects the TOC structure. When you have an article page open, the available PDFs shown are it and its ancestors up to the site PDF. 

![image](https://github.com/NetAppDocs/ontap-systems/assets/56453501/93c65d30-f99e-42c2-bae9-aefa8ad9bd07)

Something in the sidebar structure of this site is causing the PDF menu to show two nodes. This is confusing and could cause incomplete or incorrect PDF content. 

An article (topic) should exist exactly one time in the TOC.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jsnyder** [comment]
This was fixed in PR #187
