### ISSUE TITLE
Typo in page description [Overiew of controller...]

### ISSUE THREAD

**Issue by amadorloureiro** [NetAppDocs/ontap-systems#176]
### Page URL

https://docs.netapp.com/us-en/ontap-systems/fas8200/controller-replace-overview.html

### Page title

Overiew of controller module replacement - FAS8200

### Summary

There is a typo in this page, with:

> "Overiew of controller..."

instead of 

> "Over**v**iew of controller..."

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @amadorloureiro, thank you for bringing this to our attention. The typo is now corrected.
