### ISSUE TITLE
Update "Replace PDUs" document?

### ISSUE THREAD

**Issue by JamieLove-Net2** [NetAppDocs/ontap-systems#179]
### Page URL

https://docs.netapp.com/us-en/ontap-systems/platform-supplemental/42u-1280mm-replace-pdus.html

### Page title

Replace PDUs

### Summary

Would it be possible to add some verbiage and steps regarding pre-work activities before the procedure to replace the PDU or indicate that the PDU replacement will require a complete outage of all connected, powered-on equipment?
Would it also be helpful to create a new document for situations where a single PDU is being replaced in a two-PDU cabinet?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by dougthomp** [comment]
Changes made and incorporated in the doc, per our email discussion.
