### ISSUE TITLE
Incorrect link for ASA Technical Report

### ISSUE THREAD

**Issue by liamp-sys** [NetAppDocs/ontap-systems#193]
### Page URL

https://docs.netapp.com/us-en/ontap-systems/allsan-a-series/index.html

### Page title

All SAN Array (ASA) A-series Systems

### Summary

The link for the ASA technical report points to an old document.
The new ASA technical report link is now https://www.netapp.com/pdf.html?item=/media/85671-tr-4968.pdf

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jsnyder** [comment]
Thanks for bringing this to our attention. We will update to point to the new ASA TR.
