### ISSUE TITLE
Need to remove AFF C190 from AFF C-series Systems

### ISSUE THREAD

**Issue by kaminis85** [NetAppDocs/ontap-systems#196]
### Page URL

https://docs.netapp.com/us-en/ontap-systems/aff-cseries/index.html

### Page title

AFF C-series Systems

### Summary

In NetApp Hardware Universe https://hwu.netapp.com/, AFF C190 is listed under AFF A-series storage systems. So we need to put AFF C190 under AFF A-series Systems documentation page https://docs.netapp.com/us-en/ontap-systems/aff-aseries/index.html

AFF C190 needs to be removed from AFF C-series docs page.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jsnyder** [comment]
@kaminis85 C190 is EOA and has been moved the EOA section on the doc site: https://docs.netapp.com/us-en/ontap-systems/endofavail/index.html

**Comment by kaminis85** [comment]
Thanks @netapp-jsnyder
