### ISSUE TITLE
ontap-internal access rights issue

### ISSUE THREAD

**Issue by netapp-lisa** [NetAppDocs/ontap-systems#200]
### Summary

I have working branches in the ontap-internal repo. Per instructions I was trying (for the first time) to do the weekly pull of hotfixes into my working branches, but it looks like I have an access issue. See attached GitBash session.
<img width="442" alt="image" src="https://github.com/NetAppDocs/ontap-systems/assets/77256372/13a5236e-0b5b-43ca-83c7-0f760dade779">

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lisa** [comment]
Was resolved.

**Comment by ntap-bmegan** [comment]
Removing from public issues project and transferring to the internal repo for storage as this is nothing to do with content.
