### ISSUE TITLE
mentions of rest of MSID before placing a PCIe card

### ISSUE THREAD

**Issue by JMnetapp** [NetAppDocs/ontap-systems#213]
### Page URL

https://docs.netapp.com/us-en/ontap-systems/a400/pci-cards-and-risers-replace.html

### Page title

Replace a PCIe or mezzanine card - AFF A400

### Summary

Why are we telling people to reset MSID before replacing a PCIe card??

About this task
•	If you are using NetApp Storage Encryption, you must have reset the MSID using the instructions in the [Returning SEDs to unprotected mode](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.netapp.com%2Fus-en%2Fontap%2Fencryption-at-rest%2Freturn-seds-unprotected-mode-task.html&data=05%7C01%7CJeffrey.Mamuscia%40netapp.com%7C5b7791a1f0fa4cb9bd4708dbeb93e5dd%7C4b0911a0929b4715944bc03745165b3a%7C0%7C0%7C638362792689120731%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kZhNtPI4OrQZMvertQUhf1By%2FGFs3ZrfUla4Luq9iwM%3D&reserved=0).

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by dougthomp** [comment]
Removed  the prereq text (from multiple flyers):

 “If you are using NetApp Storage Encryption, you must have reset the MSID using the instructions in the [Returning SEDs to unprotected mode](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.netapp.com%2Fus-en%2Fontap%2Fencryption-at-rest%2Freturn-seds-unprotected-mode-task.html&data=05%7C02%7CDoug.Thompson%40netapp.com%7Ce8f298f5274d44f8e85208dc5fed2454%7C4b0911a0929b4715944bc03745165b3a%7C0%7C0%7C638490719318879675%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=j6Flel8d9ikahDhreive%2BncY2k1a%2FYnQlD7gKnHPS0k%3D&reserved=0).”
