### ISSUE TITLE
Cable position Incorrect

### ISSUE THREAD

**Issue by CarloAttana** [NetAppDocs/ontap-systems#214]
### Page URL

https://docs.netapp.com/us-en/ontap-systems/c250/install-detailed-guide.html

### Page title

Detailed steps - AFF C250

### Summary

In step, Step 3: Cable controllers to cluster then Step 1. you have Cable the cluster interconnect ports e0c to e0c and e0d to e0 with the 25GbE cluster interconnect cable. It should be e0d to e0d not e0.
Thanks 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-martyh** [comment]
@dougthomp and @netapp-marcis to review.

**Comment by netapp-martyh** [comment]
Reassigning to @netapp-lisa for a250 and c250.

**Comment by netapp-lisa** [comment]
@netapp-martyh, @CarloAttana Thanks Carlo, I've made the correction and corrected the location of the cable connector graphic too. The updated AFF C250 detailed install doc will go live this Friday.

**Comment by CarloAttana** [comment]
Thanku!

Get Outlook for Android<https://aka.ms/AAb9ysg>

 
Carlo Attana
Support Engineer
Interactive Pty Ltd
Telephone +61 3 9921 8444
Mobile +61 421 851 349
interactive.com.au
-------Confidentiality & Legal Privilege-------------
"This email is intended for the named recipient only. The information contained in this message may be confidential, or commercially sensitive. If you are not the intended recipient you must not reproduce or distribute any part of the email, disclose its contents to any other party, or take any action in reliance on it. If you have received this email in error, please contact the sender immediately. Please delete this message from your computer. Confidentiality and legal privilege are not waived or lost by reason of mistaken delivery to you." [v6-22112021]
________________________________
