### ISSUE TITLE
We shouldn't document say "must do" rather "Best practice considerations" regrading shelf add procedure.

### ISSUE THREAD

**Issue by awsome82** [NetAppDocs/ontap-systems#215]
### Page URL

https://docs.netapp.com/us-en/ontap-systems/sas3/install-hot-add-shelf.html

### Page title

Hot-add a shelf - shelves with IOM12/IOM12B modules

### Summary

We shouldn't document say "must do" rather "Best practice considerations" regrading shelf add procedure? 
Shelf version mismatch led to severe performance impact. 

relevant KB
https://kb.netapp.com/onprem/ontap/Performance/High_latency_when_adding_shelf

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-martyh** [comment]
Thank you for the input -- we will investigate.

**Comment by netapp-lisa** [comment]
Hi, I'm looking into this with my storage subject matter experts. In the meantime, I've been asked to remove the case no. from this public issue.

**Comment by netapp-lisa** [comment]
@netapp-martyh After checking with my storage engineers, this latency issue due to mismatched FW on IOMs in the same shelf after a hot-add is a corner case - uncommon occurrence. The shelf FW item should stay in the Best practice section.
