### ISSUE TITLE
Missing EFI/BOOT folders in downloaded ONTAP service images

### ISSUE THREAD

**Issue by amadorloureiro** [NetAppDocs/ontap-systems#220]
### Page URL

https://docs.netapp.com/us-en/ontap-systems/c250/bootmedia-replace.html

### Page title

Replace the boot media - AFF C250

### Summary

Please, check and consider to add a note with https://kb.netapp.com/onprem/ontap/hardware/EFI_folder_missing_from_Service_Image_download_file_used_for_boot_device_recovery_for_FAS_and_AFF_models

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-martyh** [comment]
Thank you for your input -- we will take a look at the KB and evaluate.

**Comment by dougthomp** [comment]
Note added to AFF A400, FAS8300, FAS8700, AFF A320, AFF A800 and AFF C250 flyers with link to the KB.

Closing issue.
