### ISSUE TITLE
Need to add PSU <-> PDU graphic for 4 PSU power cabling

### ISSUE THREAD

**Issue by andris-ntap** [NetAppDocs/ontap-systems#222]
### Page URL

https://docs.netapp.com/us-en/ontap-systems/fas9000/install-detailed-guide.html

### Page title

Detailed guide - FAS9000

### Summary

As part of this step:

2. Plug the power cords into the controller power supplies, and then connect them to power sources on different circuits.

Please add the PSU cabling to PDU graphic in the ISI PDF. It's important to clarify...
https://docs.netapp.com/us-en/ontap-systems/media/PDF/215-15154_2020-12_en-us_FAS9000_ISI.pdf

![image](https://github.com/NetAppDocs/ontap-systems/assets/84108159/5438f519-eb28-44a3-bed1-6b17f4e7745a)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-martyh** [comment]
Thanks, Andris, we will address this.

**Comment by netapp-martyh** [comment]
@dougthomp to act on this.

**Comment by dougthomp** [comment]
Artwork added.  Closing issue.
