### ISSUE TITLE
PDF SAS cabling diagram wrong

### ISSUE THREAD

**Issue by ReneMeier** [NetAppDocs/ontap-systems#223]
### Page URL

https://docs.netapp.com/us-en/ontap-systems/fas2800/install-quick-guide.html

### Page title

Quick guide - FAS2800

### Summary

In the PDF, section SAS cabling, the diagram for the Shelf to controllers has a mismatch between table view and visualization view. As an example: On the left side (table view) the blue line goes from Controller A Port 0a to Shelf 1 IOMA Port 1. On the right side (visualization) the blue line goes from Controller A Port 0a to Shelf 1 IOM _B_ Port 1.

![Image 001](https://github.com/NetAppDocs/ontap-systems/assets/74290973/d8162294-c4a4-4fa4-8b98-8ee107e5fed7)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by dougthomp** [comment]
Marci has been flagged on this.

**Comment by dougthomp** [comment]
Table corrected and doc published in ISI branch.  Will post tentatively next week.  Closing issue.

**Comment by ReneMeier** [comment]
I checked the document. Still the old (wrong) one here.

**Comment by dougthomp** [comment]
Docs are published now.
