### ISSUE TITLE
No max/min mounting depth info?

### ISSUE THREAD

**Issue by flexdataSolutions** [NetAppDocs/ontap-systems#230]
### Page URL

https://docs.netapp.com/us-en/ontap-systems/platform-supplemental/superrail-install.html

### Page title

SuperRail kit installation instructions

### Summary

Hi, there is no minimum and maximum mounting depth for these rail kits noted on this page. (i.e. how far apart the front and rear mounting flanges on the rack cabinet can be). 
I can't find this info on HWU either?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by dougthomp** [comment]
The minimum depth between front and rear connection points for installing SuperRail is 24 inches and while the maximum depth is 32 inches.

SuperRail flyer has been updated and will be published week of 3 June.  Marking issue closed.
