### ISSUE TITLE
Image is missing

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/ontap-systems#231]
### Page URL

https://docs.netapp.com/us-en/ontap-systems/asa-c800/install-detailed-guide.html

### Page title

Detailed steps - ASA C800

### Summary

![image](https://github.com/NetAppDocs/ontap-systems/assets/18287750/8caccfd8-b00f-4da4-b96b-5a6dadfed8ce)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by dougthomp** [comment]
Added a line break.  Graphic is now showing up in output:

https://review.docs.netapp.com/us-en/ontap-systems_dougt-hotfix-26feb2024/c800/install-detailed-guide.html#step-2-install-the-hardware

Will close when PR is created.

**Comment by netapp-jsnyder** [comment]
@dougthomp This image is still missing. Can you please fix.

**Comment by dougthomp** [comment]
I'm getting the image just fine.  

![image](https://github.com/NetAppDocs/ontap-systems/assets/76076341/c7b86f44-ddc4-435d-8b6a-b0672a18b6c3)

**Comment by netapp-martyh** [comment]
Doug, note that the error is in https://review.docs.netapp.com/us-en/ontap-systems_dougt-hotfix-26feb2024/**asa-c800**/install-detailed-guide.html#step-2-install-the-hardware

Not in https://review.docs.netapp.com/us-en/ontap-systems_dougt-hotfix-26feb2024/**c800**/install-detailed-guide.html#step-2-install-the-hardware, which you link above.

That said, it seems to be correct on the public site: https://docs.netapp.com/us-en/ontap-systems/asa-c800/install-detailed-guide.html#step-2-install-the-hardware

**Comment by netapp-jsnyder** [comment]
Resolved in PR #236
