### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/ontap-systems#232]
### Page URL

https://docs.netapp.com/us-en/ontap-systems/asa-c800/install-quick-guide.html

### Page title

Quick steps - ASA C800

### Summary

The link to the ISI is broken. I'm getting a 404

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by dougthomp** [comment]
I'll look at it.

**Comment by dougthomp** [comment]
The link is correct in the code and s coming up fine for me in docs.netapp.com.  Might have been a connection problem on your side.  Closing the issue.

**Comment by netapp-jsnyder** [comment]
@dougthomp This link is still broken. Can you please investigate.

**Comment by dougthomp** [comment]
I just clicked the link again and had no issue...the ISI comes up fine.  I'm going to have Marci try and see if she runs into that issue.

**Comment by netapp-jsnyder** [comment]
Resolved in PR #236
