### ISSUE TITLE
Export to PDF

### ISSUE THREAD

**Issue by TimMcGue** [NetAppDocs/ontap-systems#234]
### Page URL

https://docs.netapp.com/us-en/ontap-systems/sas3/service-replace-drawer-ds460c.html

### Page title

Replace a drive drawer in a DS460C disk shelf - shelves with IOM12/IOM12B modules

### Summary

A customer asked me today if we can make just this section (replacing a shelf) able to export to PDF instead of the entire Maintain section.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jsnyder** [comment]
@TimMcGue Thank you for your feedback! Currently, this feature is not supported. However, I recommend the following steps to achieve a similar result:

1. Hide the sidebars on the webpage you want to save.
2. Open the Chrome Menu (usually represented by three vertical dots in the top-right corner).
3. Click the “Print” option.
4. In the print dialog, change the Print Destination to “Save as PDF”.
5. Click the “Save” button to save the webpage as a PDF file.

**Comment by TimMcGue** [comment]
Makes sense!  Thank you.
