### ISSUE TITLE
Add information about replacing the secondary boot device on AFF A700s

### ISSUE THREAD

**Issue by andris-ntap** [NetAppDocs/ontap-systems#245]
### Page URL

https://docs.netapp.com/us-en/ontap-systems/a700s/bootmedia-replace-overview.html

### Page title

Overview of boot media replacement - AFF A700s

### Summary

Here's the KB that tells you how to replace the secondary boot device on an AFF A700s.
https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_replace_the_secondary_boot_device_of_an_a700s

It would be nice to add a sentence/paragraph about "If the secondary boot device needs to be replace", see the KB.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-martyh** [comment]
@netapp-ivanad, please make this update to the A700s. It is the only platform that needs this update. Ping @dougthomp if you have any questions.
