### ISSUE TITLE
Add info for adding replacement licenses with NLF files

### ISSUE THREAD

**Issue by dismn8r** [NetAppDocs/ontap-systems#258]
### Page URL

https://docs.netapp.com/us-en/ontap-systems/c800/controller-replace-restore-system-rma.html

### Page title

Complete system restoration - AFF C800

### Summary

Most licenses these days are provided via NLF file rather than 28 character key.  Info for adding replacement licenses should include, and actually focus, on this method.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-martyh** [comment]
Thanks for sharing this feedback. We will investigate this and make changes as necessary.

**Comment by dougthomp** [comment]
Note from Issue # 291 propagated to License topics.
Here's the note:

image

Closing issue
