### ISSUE TITLE
Image and formatting errors on this page

### ISSUE THREAD

**Issue by andris-ntap** [NetAppDocs/ontap-systems#260]
### Page URL

https://docs.netapp.com/us-en/ontap-systems/a1k/install-cable.html

### Page title

Cable the hardware - AFF A1K

### Summary

Howdy... there's some weird formatting/image issue on this page:
https://docs.netapp.com/us-en/ontap-systems/a1k/install-cable.html#step-1-cable-controllers-to-your-network
 
Cluster/HA interconnect cables
 
+ image::../media/drw_a1k_tnsc_cluster_cabling_ieops-1648.svg[Two-node switchless cluster cabling diagram,width=500px]
+ . Cable the Ethernet module ports to your host network.
+ The following are some typical host network cabling examples. See  [NetApp Hardware Universe](https://hwu.netapp.com/) for your specific system configuration.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-martyh** [comment]
Thanks, Andris. We've resolved this and the updates should be published this week.
