### ISSUE TITLE
Image and formatting issues on this A90-A70 page

### ISSUE THREAD

**Issue by andris-ntap** [NetAppDocs/ontap-systems#261]
### Page URL

https://docs.netapp.com/us-en/ontap-systems/a70-90/install-cable.html

### Page title

Cable the hardware - AFF A70, AFF A90

### Summary

+ image::../media/drw_70-90_tnsc_cluster_cabling_ieops-1653.svg[Two-node switchless cluster cabling diagram, width=500px]
+ . Cable the Ethernet module ports to your host network.
+ The following are some typical host network cabling examples. See  [NetApp Hardware Universe](https://hwu.netapp.com/) for your specific system configuration.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-martyh** [comment]
Thanks, Andris. We've resolved this and the updates should be published this week.
