### ISSUE TITLE
Motherboard insertion proceedure doesn't match MB swap document

### ISSUE THREAD

**Issue by SasquatchVA** [NetAppDocs/ontap-systems#268]
### Page URL

https://docs.netapp.com/us-en/ontap-systems/c800/pci-cards-and-risers-replace.html

### Page title

Replace a PCIe card - AFF C800

### Summary

Step 4: Reinstall the controller module
doesn't match the process if you were replacing the whole MB instead of just the PCI card.
I believe the MB replacement process to be more correct where we install the MB without power cable until a later point in the process.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by andris-ntap** [comment]
Yes, any FRU replacement procedures that involve the MB being removed and re-installed should all use the same consistent procedure (as currently correctly documented in the MB replacement procedure).

**Comment by dougthomp** [comment]
Done.  Will go live next week.
