### ISSUE TITLE
Please add how many Rack Units the chassis requires

### ISSUE THREAD

**Issue by aneises1** [NetAppDocs/ontap-systems#273]
### Page URL

https://docs.netapp.com/us-en/ontap-systems/c800/install-detailed-guide.html

### Page title

Detailed steps - AFF C800

### Summary

For an example see the A70 install guide. -->  https://docs.netapp.com/us-en/ontap-systems/a70-90/install-prepare.html#step-1-prepare-the-site

Step 1: Prepare the site
Make sure that the site and the cabinet or rack you plan to use meet the specifications for your storage system.

Steps
Confirm that your site meets the environmental and electrical requirements for your platform as shown in the [NetApp Hardware Universe](https://hwu.netapp.com/).

Make sure you have adequate rack space:

4U for the platform chassis

2U for each NS224 shelf

Install any required network switches near the platform.

See the [Switch documentation](https://docs.netapp.com/us-en/ontap-systems-switches/index.html) for installation instructions and [NetApp Hardware Universe](https://hwu.netapp.com/) for compatibility information.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by dougthomp** [comment]
@aneises1 
Thanks for the feedback.  We can add the space requirements data to this doc (I will, as requested).  However, there is a link to the NetApp Hardware Universe, where this information is also available.
