### ISSUE TITLE
Need to clarify that ONTAP version they are using SUPPORTS NVE - not whether NVE is enabled

### ISSUE THREAD

**Issue by andris-ntap** [NetAppDocs/ontap-systems#274]
### Page URL

https://docs.netapp.com/us-en/ontap-systems/a900/bootmedia_replace.html

### Page title

Remove the controller, replace the boot media, and transfer the boot image - AFF A900

### Summary

Sorry if this means bulk changes, but this comment is generic to all platform model "Replace" docs covering the NVE/NODAR ONTAP support topic.

Currently, the content guides the admin to select the ONTAP DAR v.s. NODAR variant by checking if NVE is enabled.
This is incorrect guidance... NVE status (enabled/disabled) is not the correct test.

The correct test is to check the ONTAP image's support of data-at-rest encryption (DAR) or not.
Point to this page for the official steps: https://docs.netapp.com/us-en/ontap/encryption-at-rest/cluster-version-support-nve-task.html

Proposed new text (to be reused for all platforms for this topic).

A copy of the same image version of ONTAP as what the impaired controller was running. You can download the appropriate image from the Downloads section on the NetApp Support Site. 

Check whether the currently running ONTAP image supports NetApp Volume Encryption: https://docs.netapp.com/us-en/ontap/encryption-at-rest/cluster-version-support-nve-task.html

    If NVE is supprted, download the image with NetApp Volume Encryption, as indicated in the download button.

    If NVE is not supported, download the image without NetApp Volume Encryption, as indicated in the download button.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by dougthomp** [comment]
Thanks Andris  I'll make the changes as soon as I can.

**Comment by dougthomp** [comment]
Changes made and will be published this week.  

Closing issue as completed.
