### ISSUE TITLE
A70 Doc misprint

### ISSUE THREAD

**Issue by bduvall02** [NetAppDocs/ontap-systems#276]
### Page URL

https://docs.netapp.com/us-en/ontap-systems/a70-90/install-cable.html

### Page title

Cable the hardware - AFF A70, AFF A90

### Summary

Under Step 1.b. it states 'Cable port e7a on Controller A to port e1A on Controller B'.  This should be cabling e7a on Controller A to e7a on Controller B.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by dougthomp** [comment]
Correction made.  The correction will appear on Tuesday, 9/24.
