### ISSUE TITLE
Need to add installation warning for issue CONTAP-285173

### ISSUE THREAD

**Issue by andris-ntap** [NetAppDocs/ontap-systems#278]
### Page URL

https://docs.netapp.com/us-en/ontap-systems/a150/install-setup.html

### Page title

Start here: Choose your installation and setup experience

### Summary

Please add the following paragraph to this AFF A150 "Start" page, as well as in the "Detailed Steps" start page:
https://docs.netapp.com/us-en/ontap-systems/a150/install-detailed-guide.html

**Warning:**
If your system is being installed with ONTAP 9.13.1P8 - 9.13.1P11, ONTAP 9.14.1P1 - 9.14.1P7 or ONTAP 9.15.1 - 9.15.1P2 and your system contains 10 or more internal solid-state drives, you must take additional steps to prepare the system for installation. See issue [CONTAP-285173](https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-285173) - ADP does not leave a spare root partition on an AFF A150 with 10 or more internal drives.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by dougthomp** [comment]
Lisa:

I’m working on this. I assigned the issue to me.
________________________________

**Comment by netapp-lisa** [comment]
Oh, okay. When I opened the issue it showed no one assigned. Weird.

**Comment by dougthomp** [comment]
Weird.  I had assigned myself to it and I wasn't there.  I re-did it.  🙄


Thanks,

Doug



________________________________

**Comment by andris-ntap** [comment]
Unfortunately, we'll also need to provide the same updates and information for the ASA A150 installation docs.
https://docs.netapp.com/us-en/ontap-systems/asa150/install-setup.html 
and its sub-pages.

**Comment by dougthomp** [comment]
Content added as discussed in TEAMS.  It will show up in this weeks build. Closing issue.
