### ISSUE TITLE
9.16.1 should be changed to 9.16.0 and FAS70, FAS90 will ship with 9.15.1 

### ISSUE THREAD

**Issue by loganbaez** [NetAppDocs/ontap-systems#281]
### Page URL

https://docs.netapp.com/us-en/ontap-systems/whats-new.html

### Page title

What's new for ONTAP hardware systems

### Summary

1. 9.16.0 is the official release 
2. FAS70, FAS90 will release with 9.15.1GA

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by dougthomp** [comment]
@loganbaez 

Official release is what we reference in the documentation. Closing issue.
