### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by SPGoetze** [NetAppDocs/ontap-systems#284]
### Page URL

https://docs.netapp.com/us-en/ontap-systems/whats-new.html

### Page title

What's new for ONTAP hardware systems

### Summary

<html><body>

ASA C800 | ONTAP 9.13.P11
-- | --

</body>
</html>[ASA C800](https://www.netapp.com/data-storage/all-flash-san-storage-array/)
	

ONTAP 9.13.P11

Should be:

<html><body>

**ASA C800 | ONTAP 9.13.1P1**
-- | --

</body>
</html>[ASA C800](https://www.netapp.com/data-storage/all-flash-san-storage-array/)
	

**ONTAP 9.13.1P1**

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jsnyder** [comment]
Thanks @SPGoetze I will get this corrected.
