### ISSUE TITLE
broken video

### ISSUE THREAD

**Issue by spruch305** [NetAppDocs/ontap-systems#288]
### Page URL

https://docs.netapp.com/us-en/ontap-systems/ns224/service-replace-drive.html

### Page title

Hot-swap a drive - NS224 shelves

### Summary

Video link is broken

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lisa** [comment]
We noticed that all of the FRU videos for NS224 stopped working. It was an issue caused by adding alt text. Ivana fixed this and the changes will go live this month.
