### ISSUE TITLE
Need to add NLF info 

### ISSUE THREAD

**Issue by andris-ntap** [NetAppDocs/ontap-systems#291]
### Page URL

https://docs.netapp.com/us-en/ontap-systems/a1k/system-management-replace.html

### Page title

Replace System management module - AFF A1K

### Summary

In this section: https://docs.netapp.com/us-en/ontap-systems/a1k/system-management-replace.html#step-4-install-licenses-and-register-serial-number

You only cover legacy (28-character) license keys.

NetApp License File (NLF) is used with ONTAP 9.10.1 and later.

Info:
KB: https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/Post_Motherboard_Replacement_Process_to_update_Licensing_on_a_AFF_FAS_system

Doc: https://docs.netapp.com/us-en/ontap/task_admin_enable_new_features.html

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by dougthomp** [comment]
Based on your note, it looks like anything running 9.10.1 and later, not just introduced with 9.10.1 and later.  Correct?

**Comment by andris-ntap** [comment]
You can limit to models introduced in 9.10.1 and later.
If the system was initially using older ONTAP, the licenses would be in the legacy format, even after ONTAP upgrades.

**Comment by dougthomp** [comment]
Andris approved the change.  Closing issue.
