### ISSUE TITLE
Missing / Bad links

### ISSUE THREAD

**Issue by michelef-netapp** [NetAppDocs/ontap-systems#33]
Page: [FAS8300 and FAS8700 System Documentation](https://docs.netapp.com/us-en/ontap-systems/fas8300/index.html)

Following links are bad under the Maintain section:
- Fan   (should be: https://docs.netapp.com/us-en/ontap-systems/fas8300/fan-swap-out.html)
- NVDIMM (should be: https://docs.netapp.com/us-en/ontap-systems/fas8300/nvdimm-replace.html)
- NVDIMM Battery (should be: https://docs.netapp.com/us-en/ontap-systems/fas8300/nvdimm-battery-replace.html)
- Power Supply (should be: https://docs.netapp.com/us-en/ontap-systems/fas8300/power-supply-replace.html)

**Comment by netapp-martyh** [comment]
Michelle - thanks for catching these! We always appreciate the feedback.

Doug, could you take a look at these?

Thanks,
Marty

**Comment by dougthomp** [comment]
Michelle - 

The links look like they're going to the right articles.  I just opened all 4 of the articles and they opened properly.  What kind of error did you get?

This is what I got when I clicked on the 8300 Fan flyer:

![image](https://user-images.githubusercontent.com/76076341/142711512-d2a7c178-3aed-468c-8486-ec845a385ec6.png)

Doug

**Comment by dougthomp** [comment]
Yes - back in Nove,ber.  Closing issue.
