### ISSUE TITLE
Request to add the disclaimer about environmental shutdown if FANs are not replaced within 2 minutes

### ISSUE THREAD

**Issue by pmidhun16** [NetAppDocs/ontap-systems#38]
Page: [Hot-swap a fan module - AFF A320](https://docs.netapp.com/us-en/ontap-systems/a320/fan-swap-out.html)

I feel we should add the below disclaimer in this document  too like in AFF-A300
As of now, 2 minutes env shutdown policy is applicable to A320 also

Disclaimer:
You must replace the fan module within two minutes of removing it from the chassis. System airflow is disrupted and the controller module or modules shut down after two minutes to avoid overheating.

**Comment by dougthomp** [comment]
Thank you for your feed back.  You are correct - the paragraph has been added back to the procedure.  It will be available sometime toward the beginning of next week. 

Doug Thompson
