### ISSUE TITLE
PDF link broken (404) for "Information for cabling switch-attached NS224 drive shelves"

### ISSUE THREAD

**Issue by andris-ntap** [NetAppDocs/ontap-systems#40]
Page: [Cable shelves as switch-attached storage - NS224 shelves](https://docs.netapp.com/us-en/ontap-systems/ns224/cable-as-switch-attached.html)

Link: Information for cabling switch-attached NS224 drive shelves
for PDF URL: https://library.netapp.com/ecm/ecm_download_file/ECMLP2876580
appears to be broken. It redirects to "404 not found" page:
https://www.netapp.com/support-and-training/documentation/ecm/ecm_download_file/ECMLP2876580/

I tried to figure out where it went - can't find it. Please fix. 

Thanks!
-Andris

**Comment by netapp-martyh** [comment]
Hi Andris - I think this was a temporary issue, it looks like its working now. Please let us know if you still see the issue; if not, we'll close this.

**Comment by andris-ntap** [comment]
This is working now. You can close it.

Thanks
-Andris

**Comment by netapp-martyh** [comment]
Thanks for confirming.
