### ISSUE TITLE
Bad link for "Power Supply" in main A700/FAS9000 page

### ISSUE THREAD

**Issue by andris-ntap** [NetAppDocs/ontap-systems#43]
Page: [AFF A700 and FAS9000 System Documentation](https://docs.netapp.com/us-en/ontap-systems/fas9000/index.html)

Power supply link is: https://docs.netapp.com/us-en/ontap-systems/fas9000/power-supply-swapout.html

The correct link is (with the extra dash): https://docs.netapp.com/us-en/ontap-systems/fas9000/power-supply-swap-out.html

**Comment by dougthomp** [comment]
I'll take it,

**Comment by dougthomp** [comment]
Issue corrected back in December.  Marking this as closed.
