### ISSUE TITLE
Search isn't working on public docs

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/ontap-systems#44]
Page: [AFF and FAS System Documentation](https://docs.netapp.com/us-en/ontap-systems/index.html)

I get this:

![image](https://user-images.githubusercontent.com/56453501/146002714-a8d131ac-a9a7-4295-b350-4a9a114620c3.png)

**Comment by netapp-martyh** [comment]
Restarted the main build as mentioned in https://github.com/NetAppDocs/docs-help/discussions/295

1. Went to https://app.travis-ci.com/github/NetAppDocs/ontap-systems.
2. Restarted the most recent build of main.
![image](https://user-images.githubusercontent.com/66496079/146085322-209c57e1-7dbd-42a2-8699-8bd9d2e5f1d5.png)

This resolved the issue.
