### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by loganbaez** [NetAppDocs/ontap-systems#46]
Page: [Other platform models](https://docs.netapp.com/us-en/ontap-systems/other/platform-linkout.html)

- All the links are broken except for the AFF 8000. 
- the broken links fail with the following message

_upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: immediate connect error: 101_

thank you

**Comment by loganbaez** [comment]
any update on this

**Comment by netapp-martyh** [comment]
Hi Logan -

Sorry for the delay. The Other platform models page has been replaced by the Other models page:
https://docs.netapp.com/us-en/ontap-systems/other/other-models.html
