### ISSUE TITLE
System data sheet is missing A900 info

### ISSUE THREAD

**Issue by loganbaez** [NetAppDocs/ontap-systems#52]
Page: [AFF A900 systems](https://docs.netapp.com/us-en/ontap-systems/a900/index.html)

**Comment by dougthomp** [comment]
I have contacted the owner of the Datasheet, Ling Wang.  I have requested an update.

**Comment by dougthomp** [comment]
@loganbaez 

Logan:
The datasheet was updated and released when AFF A900 was announced, according to Marketing.  When I looked yesterday at our link, I didn't see it, as you indicated. This morning, I looked and AFF A900 is there.  The URLs are the same, so there must have been some sort synchronization issue. 

Sorry for the inconvenience.  I'm not sure what happened, but I will check into it more.

**Comment by dougthomp** [comment]
@akseldavis 

What would cause this to happen?

**Comment by thrisun** [comment]
I think that for a URL to show the updated information, it would have required us to make sure our merges go public for it to pull it in. Just my $0.02. :-)

**Comment by dougthomp** [comment]
The URLs were identical, so that should have made no difference, unless something funky was going on.  If that's the case, we should have received a 404 error.  Would be nice to know what that "funky" is and figure out how to avoid it in the future.  But that's avoiding something that shouldn't have happened.

**Comment by akseldavis** [comment]
@dougthomp The last change to that link was 3 months ago. Let's follow-up internally about the specific behavior you are experiencing and we can report back here, if needed.
