### ISSUE TITLE
Missing content?

### ISSUE THREAD

**Issue by jenatnetapp** [NetAppDocs/ontap-systems#53]
Page: [Detailed guide - AFF A220 and FAS2700](https://docs.netapp.com/us-en/ontap-systems/fas2700/install-detailed-guide.html)

![image](https://user-images.githubusercontent.com/48109805/151869602-80aa71cc-d858-4c4a-a665-8da81d93a7e8.png)

Should there be text in this empty row with the "caution!" icon?

**Comment by dougthomp** [comment]
Caution text added and will go live next week.
