### ISSUE TITLE
FAS2700 System Data Sheet Link goes to FAS2600 document

### ISSUE THREAD

**Issue by netapp-adlove** [NetAppDocs/ontap-systems#55]
Page: [AFF A220 and FAS2700 System Documentation](https://docs.netapp.com/us-en/ontap-systems/fas2700/index.html)

FAS2700 System Data Sheet Link goes to FAS2600 document here: https://www.netapp.com/media/8936-ds-3808.pdf

**Comment by dougthomp** [comment]
We have corrected the link and it will be available early next week.  We apologize for any inconvenience this may have caused.
