### ISSUE TITLE
Question on wording

### ISSUE THREAD

**Issue by TimMcGue** [NetAppDocs/ontap-systems#60]
Page: [Transfer the boot image to the boot media - AFF A800](https://docs.netapp.com/us-en/ontap-systems/a800/bootmedia-transfer-boot-image.html)

The USB flash drive should have the efi folder and the same Service Image (BIOS) version of what the impaired controller is running.

So in this line.  The "and the same" is kind of where I am hung up at.  I think what we are trying to convey there is the EFI folder should be extracted from the same BIOS version the impaired controller is running.  When I read "and the same" it makes me think I should put both the EFI folder and a copy of the BIOS itself on the USB drive.  Maybe I'm just reading it wrong, but wanted to share in case I am not alone.  

Thanks as always for your hard work on the docs!!

**Comment by thrisun** [comment]
Hi Tim, 
Thank you for contacting us on this. 
Doug and I will discuss this an provide clarity on the verbiage.
Thank you again for helping us improve our docs! :-)

**Comment by dougthomp** [comment]
Hi Tim:

Here's the proposed changes:  


There are two folders in the unzipped service image file:

•	boot
•	efi
**Note:**  The efi folder contains the Service image (BIOS).  Verify the Service image you download is the same version as that of the ONTAP version the impaired node was running.
c. Copy the efi folder to the top directory pm the USB fash drive.

**Comment by TimMcGue** [comment]
Sorry for the late response - I think that is great.  Active IQ now has a chart that shows BIOS by release of each version of ONTAP so even if the system didn't have AutoSupport and wasn't bootable they could cross reference from there.
