### ISSUE TITLE
Cluster cabling wrong

### ISSUE THREAD

**Issue by nlsntap** [NetAppDocs/ontap-systems#62]
Page: [Detailed guide - FAS8300 and FAS8700](https://docs.netapp.com/us-en/ontap-systems/fas8300/install-detailed-guide.html)

the pictures showing the cluster cabling are wrong. Those are A400 controllers. The card shown in slot 3 is not available for FAS8300/FAS8700 controllers. The cluster cabling goes to ports e0c and e0d on those platforms.

**Comment by dougthomp** [comment]
I've corrected the diagrams (wrong ones referenced in GitHub) and the correction will appear early next week.  Thank you for bringing this to our attention.

**Comment by netapp-martyh** [comment]
Doug - was this resolved?

**Comment by dougthomp** [comment]
Yes.  Closing the issue.
