### ISSUE TITLE
small misspelling

### ISSUE THREAD

**Issue by ericd-netapp** [NetAppDocs/ontap-systems#65]
Page: [Boot the recovery image - FAS8200](https://docs.netapp.com/us-en/ontap-systems/fas8200/bootmedia-recovery-image-boot-options.html)

Item 4, section d.

the correct command is:  saveenv or savenv

the document says:  "savenev"

**Comment by dougthomp** [comment]
Thanks Eric.  I'm correcting the typo and the change will go live April 4th, if not sooner.

**Comment by dougthomp** [comment]
Confirmed change in working branch

**Comment by ericd-netapp** [comment]
thanks doug!

Eric Davis
Americas Field Support Engineer
NCDA, NCSE, NCIE-SAN, NCSIE

NetApp
323.388.7727 Mobile Phone
***@***.******@***.***>
