### ISSUE TITLE
Under Maintain the PSU Link does not work

### ISSUE THREAD

**Issue by roscocheeta** [NetAppDocs/ontap-systems#70]
Page: [FAS2700 System Documentation](https://docs.netapp.com/us-en/ontap-systems/fas2700/index.html)

Hi Team,

On this page, under the Maintain section if you click the PSU link it throws up a 404 (link its referencing is https://docs.netapp.com/us-en/ontap-systems/fas2700/power-supply-swapout.html)

**Comment by dougthomp** [comment]
Hi Roscocheeta:

Thank you for bring this to our attention.    I've located the issue and corrected it.  The correct behavior should show up in the GitHub early next week.

**Comment by dougthomp** [comment]
Correction will appear on the week of 18 April, 2022
