### ISSUE TITLE
Add wait time for each cable un-plug/plug action

### ISSUE THREAD

**Issue by rikboers** [NetAppDocs/ontap-systems#74]
Page: [Hot-add a shelf - shelves with IOM12 modules](https://docs.netapp.com/us-en/ontap-systems/sas3/install-hot-add-shelf.html)

On this page we are lacking a wait time between each un-plug and plug action.
We do mention the requirement to finish the disk inventory when changing a shelf ID:
  "_This time allows ONTAP to properly delete the old shelf address and update the copy of the new shelf address._"
When adding a shelf we need to remove a cable which might require ONTAP to rescan the disk inventory as well.
Since we do not know which cable is un-plugged or plugged we should mention the wait time for each step.
Recommended to remain with the 70 second time as in other documents in this section.

**Comment by netapp-lisa** [comment]
Hi Rik, I think after all the emails, it's still "good" to include the 70 second wait for the shelf hot-add procedure when disconnecting one end of a cable and connecting to to a different port, and when swapping out an entire cable? See the link to the Word doc with the text additions. Let me know if you're good with this or want to make any changes.
[70seconds.docx](https://github.com/NetAppDocs/ontap-systems/files/8691792/70seconds.docx)

**Comment by rikboers** [comment]
Hi Lisa,

Waiting 70 seconds indeed will not hurt in any case.
Even if it is not absolutely required it will give a better insight in analysis why something goes wrong during a hot add of shelves.
Indeed it applies to both moving and replacing the cable.

Your addition looks good to me.

Kind Regards,
Rik Boers
Technical Support Escalation Engineer
Technical Support Center

***@***.******@***.***>

My normal working hours are Monday-to-Friday, 9:00 – 17:30 CET.

**Comment by netapp-lisa** [comment]
Great! I'll close out this issue.
