### ISSUE TITLE
FAS8200 cluster setup has wrong link

### ISSUE THREAD

**Issue by kellerth** [NetAppDocs/ontap-systems#75]
The ´Quick setup´ link in ´FAS8200 systems´--> ´Install and Setup´ --> ´Choose install and setup experience´ leads to a wrong document (JavaTM API Bindings Release Notes).

**Comment by thrisun** [comment]
Hi, 
Thank you for contacting us about this. This should be corrected by the end of this week.
Take care and keep safe.

**Comment by dougthomp** [comment]
Marking this closed.  Changes made.
