### ISSUE TITLE
404 error for A220 setup doc

### ISSUE THREAD

**Issue by estarz** [NetAppDocs/ontap-systems#79]
Page: [A220 System Documentation](https://docs.netapp.com/us-en/ontap-systems/a220/index.html)

**Comment by thrisun** [comment]
Doug, the issue is the Most Configurations link in the Install and setup tile on the AFF A220 page:
![image](https://user-images.githubusercontent.com/30325635/169100761-fe814fd6-1356-44ac-bd76-c274f49e5f17.png)
Could you please take a look at the link?
Thank you very much!

**Comment by dougthomp** [comment]
I asked Jackie to look at this because it is a landing page issue.
