### ISSUE TITLE
PCIe card not seen or is errored after new installation or replacement

### ISSUE THREAD

**Issue by mark-MetroSys** [NetAppDocs/ontap-systems#86]
Page: [Contribute to NetApp technical content in GitHub](https://docs.netapp.com/us-en/contribute/index.html)

Step 3: Reboot the controller after PCIe module replacement

After you replace a PCIe module, you must reboot the controller module.

Steps

Step 1 has the requested change. The current information is incorrect and appears to only be required for NVRAM module replacement

1. If the node is at the LOADER prompt, boot the node by entering `bye` at the loader prompt. This will reinitialize the PCIe cards and other components and reboot the node.

For step 3, the row "An HA pair" does NOT perform the same as `bye` and should be removed.

**Comment by dougthomp** [comment]
Hi Mark:

I had a similar comment/request for this issue.  The changes were made and are live in the FAS9000 repository (https://docs.netapp.com/us-en/ontap-systems/fas9000/pci-cards-and-risers-replace.html#step-3-reboot-the-controller-after-pcie-module-replacement).

I am closing the issue.

**Comment by dougthomp** [comment]
Thank you for the feedback.
