### ISSUE TITLE
Add AIQ Digital Advisor to "More Resources"

### ISSUE THREAD

**Issue by andris-ntap** [NetAppDocs/ontap-systems#96]
Page: [AFF and FAS System Documentation](https://docs.netapp.com/us-en/ontap-systems/index.html)

After "NetApp HWU" in "More Resources", I'd like add this:
[NetApp Active IQ Digital Advisor](https://docs.netapp.com/us-en/active-iq/index.html)

**Comment by thrisun** [comment]
Hi Andris, I have copied the team on this request. We will discuss this in tomorrow's SPie meeting.

**Comment by netapp-lisa** [comment]
Hey Andris, we're adding the link under HWU in the More resources box on all AFF, FAS and shelf landing pages. It should be completed by end of next week (Aug 19) or early the week after. I'll close this once the changes go live.

**Comment by netapp-lisa** [comment]
Hi Andris, the link to NetApp Active IQ Digital Advisor has been added to all AFF, FAS and shelf index/landing pages in the More resources box and the updates are now live.
