### ISSUE TITLE
Speed for mixed stacks. 

### ISSUE THREAD

**Issue by MikePalicNTAP** [NetAppDocs/ontap-systems#99]
Page: [Hot-add IOM12/IOM12B shelves to a stack of IOM6 shelves](https://docs.netapp.com/us-en/ontap-systems/sas3/iom12-hot-add-mix.html)

This came up on the community the other day - https://community.netapp.com/t5/ONTAP-Hardware/IOM12-and-IOM6-mixed-stack-path-throughput/td-p/437186

I'd agree that what speed a mixed stack needs to be put somewhere in the SAS2/SAS3 IOM6/IOM12 mixing rules pages.

**Comment by thrisun** [comment]
Hi Lisa,
Please take a look and respond to Mike.
Thank you!

**Comment by MikePalicNTAP** [comment]
Can also be added to this KB - https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/How_to_cable_an_IOM12E_platform_with_IOM6_and_IOM12_storage_shelves_in_Multi-Path_HA

**Comment by netapp-lisa** [comment]
Hi Mike, sorry for the delay. I can add the following bullet to the "Hot-add IOM12/IOM12B shelves to a stack of IOM6 shelves" procedure in the General considerations section: https://docs.netapp.com/us-en/ontap-systems/sas3/iom12-hot-add-mix.html#general-considerations
Note: I pulled this content from a "12Gb SAS SE presentation" v1.7 last updated in July. It aligns with comments in the community discussion,

•	When you hot-add shelves with IOM12 modules to a stack of shelves with IOM6 modules the performance of the entire stack operates at 6Gbs (runs at the lowest common speed) and the transport speed for data between shelves in the stack operates at 12Gbs.
Note: If the shelves you are hot-adding are shelves that have been upgraded from IOM3 or IOM6 modules to IOM12 modules, the stack operates at 12Gbs; however, the shelf backplane limits individual shelf performance to 6Gbs.

Also, I'll make a request to the KB team to update the KB.

**Comment by MikePalicNTAP** [comment]
Hey Lisa, that will work.  thank you!

**Comment by netapp-lisa** [comment]
Hi Mike, FYI, I made some changes to the text based on feedback from Doug Coatney. The bullet will read:
• When you hot-add shelves with IOM12 modules to a stack of shelves with IOM6 modules, the performance of the entire stack operates at 6 Gbps (runs at the lowest common speed).
Note: If the shelves you are hot-adding are shelves that have been upgraded from IOM3 or IOM6 modules to IOM12 modules, the stack operates at 12 Gbps; however, the shelf backplane and disk capabilities can limit disk performance to 3 Gbps or 6 Gbps.
